// Code generated by MockGen. DO NOT EDIT.
// Source: source/iterator/snapshot.go
//
// Generated by this command:
//
//	mockgen -package mock -source source/iterator/snapshot.go -destination source/iterator/mock/snapshot.go
//

// Package mock is a generated GoMock package.
package mock
